FROM nginx:1.23.2

COPY ./src /data/www

COPY ./nginx/default.dev.conf /etc/nginx/conf.d/default.conf

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/localhost.key -out /etc/ssl/certs/localhost.crt -subj "/C=CH/ST=Zurich/L=Zurich/O=DolceGustoDev/OU=Dev/CN=localhost"

EXPOSE 80
EXPOSE 443