version: "3.9"

services:
  frontend:
    build:
      context: frontend
    image: dolce-gusto-frontend

  backend:
    build:
      context: backend
    image: dolce-gusto-backend
    environment:
      - DG_USERNAME
      - DG_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
    volumes:
      - ./selenium:/selenium

  nginx:
    build:
      context: nginx
    image: dolce-gusto-nginx
    ports:
      - ${PORT}:80
    depends_on:
      - frontend
      - backend

  db:
    build:
      context: db
    image: dolce-custo-db
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - ./db-data/:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    depends_on:
      - db
